---
- name: Deploy Application with Docker
  hosts: localhost
  become: yes
  connection: local

  vars:
    app_name: "your-app"
    container_name: "{{ app_name }}-container"
    docker_image: "ke102erthi/your-app"
    docker_tag: "latest"

  tasks:
    - name: Update yum cache
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Stop existing container
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Remove old image
      docker_image:
        name: "{{ docker_image }}"
        tag: "{{ docker_tag }}"
        state: absent
      ignore_errors: yes

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "{{ docker_image }}"
        tag: "{{ docker_tag }}"
        source: pull

    - name: Run new container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}:{{ docker_tag }}"
        state: started
        restart_policy: always
        ports:
          - "80:5000"
